# =================================================
# Configuration file for the ML model parameters
# =================================================
# Author: Patrik Benacek

# Forecast leadtime
24h:
    # Model definition
    ngboost:
        model:
            n_estimators: 600
            minibatch_frac: 0.2
            learning_rate: 0.03
        learner:
            criterion: "friedman_mse"
            max_depth: 4
    qrf:
        model:
            n_estimators: 500
            max_features: 25
            min_samples_leaf: 2
            bootstrap: False
    xtr:
        model:
            n_estimators: 500
            max_features: 50
            min_samples_leaf: 2
            bootstrap: False

240h:
    ngboost:
        model:
            n_estimators: 400
            minibatch_frac: 0.1
            learning_rate: 0.01
        learner:
            criterion: "friedman_mse"
            max_depth: 2
    qrf:
        model:
            n_estimators: 500
            max_features: 10
            min_samples_leaf: 1000
            bootstrap: False
    xtr:
        model: 
            n_estimators: 500
            max_features: 40 
            min_samples_leaf: 300
            bootstrap: False
