# =================================================
# Configuration file for the ML model parameters
# =================================================
# Author: Patrik Benacek

# Forecast leadtime
24h:
    # Model definition
    ngboost:
        model:
            n_estimators: 600
            minibatch_frac: 0.1
            learning_rate: 0.01
        learner:
            criterion: "friedman_mse"
            max_depth: 10
    qrf:
        model:
            n_estimators: 500
            max_features: 27
            min_samples_leaf: 15
            bootstrap: True
    xtr:
        model:
            n_estimators: 500
            max_features: 45 
            min_samples_leaf: 8
            bootstrap: False

# (not yet examinated)
240h: 
    ngboost:
        model:
            n_estimators: 100
            minibatch_frac: 1.0
            learning_rate: 0.05
        learner:
            criterion: "friedman_mse"
            max_depth: 5
    qrf:
        model:
            n_estimators: 500
            max_features: 50 
            min_samples_leaf: 50
            bootstrap: True
    xtr:
        model: # Second best result (but faster)
            n_estimators: 700
            max_features: 40 
            min_samples_leaf: 10
            bootstrap: False
